version: "3.8"
services:

    marketplace:
        # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
        #                   -t marketplace --secret id=ca.key,src=ca.key
        environment:
            RECOMMENDATIONS_HOST: recommendations
        image: szekler/marketplace:latest
        networks:
            - microservices
        ports:
            - 5000:5000

    recommendations:
        # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
        #                   -t recommendations --secret id=ca.key,src=ca.key
        image: szekler/recommendations:latest
        networks:
            - microservices

networks:
    microservices:
