---
apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  selector:
    app: recommendations
  ports:
    - name: grpc
      protocol: TCP
      port: 443
      targetPort: 443
